no_of_epochs: 45
learning_rate: 0.0001
train_batch_size: 2
test_batch_size: 1
model_name: "MIMO-Net"
GPUs: 1
threads: 0
dataset_family: "CRAG"
dataset_path: "../Datasets/CRAG/"
steps_per_epoch: 1000
image_width: 256
image_height: 256
resize: 300